### ISSUE TITLE
Document File entity 

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/pass-data-model#5]
We will need to capture the files associated with a Submission. This requires a new entity document.

**Comment by birkland** [comment]
There is a little subtlety here in distinguishing between

* files, in the sense of being binaries, will be POSTed to Fedora as binaries.
* Files, in the sense of metadata-containing model entities

Putting a file in the repository will likely involve both, and ant File entities ought to link to the file resource they describe.  Fedora automatically creating a descriptive resource when it creates "files" (so POSting binary content actually results in the creation of two resources - the binary and its description), which we may or may not want to use.  The advantage of this mechanism is that if you do a `HEAD` request against the binary file in Fedora `http://path/to/file.txt`, it has a `describedby` header which links to the resource that describes it, e.g. `http://path/to/file.txt/fcr:metadata`.  The disadvantage is that it may be difficult to use in the Ember adapter.  So some consultation with @markpatton might be necessary in order to nail that down

**Comment by markpatton** [comment]
Yes. We may have to have on the pass side a service which understands how to persist and retrieve files from Fedora.
